version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: myapp
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: